pipeline {
    agent { docker { image 'python:3.5.1' } }
    stages {
        stage('build') {
            steps {
                sh 'echo different version'
                sh 'python --version'
            }
        }
    }
}
